package org.xenon.echo.enums;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_BLOCKED_UNVERIFIED,
    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET_SUCCESS,
    EMAIL_VERIFICATION_ALREADY_DONE,
    EMAIL_VERIFICATION_SUCCESS,
    RATE_LIMIT_HIT
}
